/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import java.awt.Color;
import Model.Majors;
import DAO.MajorsDAO;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author admin
 */
public class MajorsManagerment extends javax.swing.JPanel {

    /**
     * Creates new form MajorsManagerment
     */
    public MajorsManagerment() {
        initComponents();
        inBang();
        dataBang();
        setOpaque(false);
    }
    private DefaultTableModel tblModel;
    private void inBang()
    {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[] {"Mã Ngành", "Tên Ngành"});
        tblNganh.setModel(tblModel);
    }
    
    private void dataBang()
    {
        try 
        {
            MajorsDAO CSDL = new MajorsDAO();
            List<Majors> list = CSDL.findAll();
            tblModel.setRowCount(0);
            for(Majors it:list)
            {
                tblModel.addRow(new Object[]{
                   it.getMa_Nganh(), it.getTen_Nganh()
                });
            }
            tblModel.fireTableDataChanged();
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
//            txtThongBao.setText("Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNganh = new javax.swing.JTable();
        txtMaNganh = new CustomSwing.TextField();
        txtTenNganh = new CustomSwing.TextField();
        btnTaoMoi = new CustomSwing.Button();
        btnLuu = new CustomSwing.Button();
        btnCapNhat = new CustomSwing.Button();
        btnXoa = new CustomSwing.Button();

        bg.setBackground(new java.awt.Color(250, 250, 250));
        bg.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản Lý Ngành");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jLabel2.setText("Mã Ngành:");

        jLabel3.setText("Tên Ngành:");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tblNganh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", ""},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNganh.setGridColor(new java.awt.Color(255, 255, 255));
        tblNganh.setRowHeight(25);
        tblNganh.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tblNganh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNganhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNganh);

        btnTaoMoi.setForeground(new java.awt.Color(0, 0, 0));
        btnTaoMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_new_20px.png"))); // NOI18N
        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });

        btnLuu.setForeground(new java.awt.Color(0, 0, 0));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_add_20px_1.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat.setForeground(new java.awt.Color(0, 0, 0));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_rotate_right_20px.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(0, 0, 0));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_delete_20px.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaNganh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenNganh, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(btnTaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblNganhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNganhMouseClicked
        try
        {
            int row = tblNganh.getSelectedRow();
            if(row>=0)
            {
                String id = (String)tblNganh.getValueAt(row, 0);
                MajorsDAO CSDL = new MajorsDAO();
                Majors nganh = CSDL.findByMa_Nganh(id);

                if(nganh != null)
                {
                    txtMaNganh.setText(nganh.getMa_Nganh());
                    txtTenNganh.setText(nganh.getTen_Nganh());
                }
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
            //            txtThongBao.setText("Lỗi");
        }
    }//GEN-LAST:event_tblNganhMouseClicked

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
        txtMaNganh.setText("");
        txtTenNganh.setText("");
        //        txtThongBao.setText("");

        txtMaNganh.requestFocus();

        txtMaNganh.setBackground(Color.white);
        txtTenNganh.setBackground(Color.white);
    }//GEN-LAST:event_btnTaoMoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if(txtMaNganh.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Mã Ngành không được bỏ trống !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
            //            txtThongBao.setText("Mã Ngành không được bỏ trống");
            txtMaNganh.setBackground(Color.red);
            txtMaNganh.requestFocus();
        }
        else if(txtTenNganh.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Tên ngành không được bỏ trống !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
            //                txtThongBao.setText("Tên ngành không được bỏ trống");
            txtTenNganh.setBackground(Color.red);
            txtTenNganh.requestFocus();
        }
        else
        {
            try
            {
                Majors nganh = new Majors();
                nganh.setMa_Nganh(txtMaNganh.getText());
                nganh.setTen_Nganh(txtTenNganh.getText());

                MajorsDAO CSDl = new MajorsDAO();
                if(CSDl.insert(nganh))
                {
                    JOptionPane.showMessageDialog(null, "Thêm Ngành thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    //                        txtThongBao.setText("Thêm Ngành thành công");
                    dataBang();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Thêm Ngành không thành công !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
                    //                        txtThongBao.setText("Thêm Ngành không thành công");
                }
            }
            catch (Exception e)
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Trùng Mã Ngành !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
                //                    txtThongBao.setText("Trùng Mã Ngành");
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if(txtMaNganh.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Mã Ngành không được bỏ trống !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
            //            txtThongBao.setText("Mã Ngành không được bỏ trống");
            txtMaNganh.setBackground(Color.red);
            txtMaNganh.requestFocus();
        }
        else if(txtTenNganh.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Tên ngành không được bỏ trống !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
            //                txtThongBao.setText("Tên ngành không được bỏ trống");
            txtTenNganh.setBackground(Color.red);
            txtTenNganh.requestFocus();
        }
        else
        {
            try
            {
                Majors nganh = new Majors();
                nganh.setMa_Nganh(txtMaNganh.getText());
                nganh.setTen_Nganh(txtTenNganh.getText());

                MajorsDAO CSDl = new MajorsDAO();
                if(CSDl.update(nganh))
                {
                    JOptionPane.showMessageDialog(null, "Cập nhật thành công !!!","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    //                        txtThongBao.setText("Cập nhật thành công");
                    dataBang();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Cập nhật không thành công !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
                    //                        txtThongBao.setText("Cập nhật không thành công");
                }
            }
            catch (Exception e)
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Lỗi !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
                //                    txtThongBao.setText("Lỗi");
            }
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int hoi = JOptionPane.showConfirmDialog(null, "Bạn thật sự muốn xóa", "Thông báo", JOptionPane.YES_NO_OPTION);
        if(hoi == JOptionPane.YES_OPTION)
        {
            if(txtMaNganh.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Mã Lớp không được để trống !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
                //                txtThongBao.setText("Mã Lớp không được để trống");
                txtMaNganh.setBackground(Color.red);
                txtMaNganh.requestFocus();
            }
            else
            {
                try
                {
                    MajorsDAO CSDL = new MajorsDAO();
                    if(CSDL.delete(txtMaNganh.getText()))
                    {
                        JOptionPane.showMessageDialog(null, "Xóa thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                        //                            txtThongBao.setText("Xóa thành công");
                        dataBang();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Xóa không thành công !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
                        //                            txtThongBao.setText("Xóa không thành công");
                    }
                }
                catch (Exception e)
                {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Lỗi !!!","Lỗi",JOptionPane.ERROR_MESSAGE);
                    //                        txtThongBao.setText("Lỗi");
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private CustomSwing.Button btnCapNhat;
    private CustomSwing.Button btnLuu;
    private CustomSwing.Button btnTaoMoi;
    private CustomSwing.Button btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNganh;
    private CustomSwing.TextField txtMaNganh;
    private CustomSwing.TextField txtTenNganh;
    // End of variables declaration//GEN-END:variables
}
